### ISSUE TITLE
Current dhcpcdui.so doesn't properly detect the RealTek r8188eu Wi-Fi adapter

### ISSUE THREAD

**Issue by ramseyrt** [RPi-Distro/lxpanel#1]
Hello,

I have a Raspberry Pi Zero (v1.3) connected to a HubPiWi (which uses the RealTek r8188eu Wi-Fi chipset) running Raspbian Jessie released on 11 January 2017.  In the Raspbian Jessie builds from 23 September 2016, 25 November 2016, and 11 January 2017, the LXPanel WiFi Network plugin (dhcpcdui.so) doesn't properly detect the r8188eu wireless device.  When I click on the plugin icon, "No wireless interface found" is displayed.  When I hover over the plugin icon, "wlan0: not associated" is displayed.  I am unable to configure my wireless device because the plugin isn't detecting it properly.

The Raspbian Jessie build, released on 27 May 2016, does properly detect and behave with the HubPiWi RealTek Wi-Fi device.  When I copied over the /usr/lib/arm-linux-gnueabihf/lxpanel/plugins/dhcpcdui.so file from this old build to the current build, the WiFi Network icon worked properly.

You can see screen captures of the issue and trace through my trouble-shooting here:
https://www.raspberrypi.org/forums/viewtopic.php?p=1117702#p1117702

Cordially,

Rob Ramsey
USAF Academy, CO

**Comment by spl237** [comment]
Dear Rob, 

First off, let me thank you for such careful investigation and for the detailed and helpful bug report. This ought to be fixable - we did make some changes to that plugin last year, and while it is still fine with all the devices we tested with, clearly there is an issue with yours. I'll review all your logs over the next couple of days and see if I can find a cause and a fix. I may need to send you a version of the plugin with some debug in it to help track it down - I'll let you know if that is the case.

**Comment by ramseyrt** [comment]
Hello Simon,

I'm happy to help in any way : )

Cordially,

Rob

**Comment by spl237** [comment]
Rob,

One thing which would be helpful is if you could try the following.

Open a terminal window, and then enter "sudo pkill lxpanel" - this will close LXPanel.

Then, from the same terminal, enter "lxpanel -p LXDE-pi" - this will restart LXPanel with debug directed to the terminal.

Could you please post the output that you see from doing this on both the working 27 May version and the non-working 11 January versions of Raspbian with your HubPiWi connected. I've been reading your thread above, and a few things that you describe in there look a little odd - this may take me a while to track down,  but the output of the command above will be helpful. Many thanks in advance.

**Comment by spl237** [comment]
Incidentally - have you raised this issue with the designer of the HubPiWi? They seem to produce custom versions of Raspbian to support their products, such as this - http://referencedesigner.com/blog/software-drive-for-8gb-cards-for-hubpiwi-blue/6130/

I have in the past had issues with some wi-fi dongles not being detected by the networking plugin in LXPanel, and this was usually tracked to some part of the driver not behaving as expected - one in particular identified the (wireless) connection it provided as a wired connection, which caused all sorts of chaos. I suspect something like that will be the cause of this issue, so it is worth raising it with the designer in case they are already aware of the problem and potentially already have a fix.

**Comment by ramseyrt** [comment]
Hello Simon,

Here's the output you were looking for:

_dhcpcdui.so from 11 January 2017 Raspbian Jessie build running on 11 January 2017 OS_

pi@raspberrypi:~ $ lxpanel -p LXDE-pi
** Message: x-terminal-emulator has very limited support, consider choose another terminal
** Message: Connecting ...
** Message: Status changed to down
** Message: Status changed to opened
** Message: Connected to dhcpcd-6.7.1
** Message: Status changed to disconnected
** Message: wlan0: Not associated
** Message: wlan0: WPA status connected
** Message: wlan0: Received scan results
E: [pulseaudio] main.c: Failed to kill daemon: No such process
** Message: bt: Name org.bluez owned on DBus
** Message: bt: New agent manager found
** Message: bt: No adapter found
** Message: va: Name org.bluez owned on DBus
** Message: va: Stopping PulseAudio

_dhcpcdui.so from 27 May 2016 Raspbian Jessie build running on 11 January 2017 OS_

pi@raspberrypi:~ $ lxpanel -p LXDE-pi
** Message: x-terminal-emulator has very limited support, consider choose another terminal
** Message: Connecting ...
** Message: Status changed to down
** Message: Status changed to opened
** Message: Connected to dhcpcd-6.7.1
** Message: Status changed to disconnected
** Message: wlan0: Not associated
** Message: wlan0: Received scan results
E: [pulseaudio] main.c: Failed to kill daemon: No such process
** Message: bt: Name org.bluez owned on DBus
** Message: bt: New agent manager found
** Message: bt: No adapter found
** Message: va: Name org.bluez owned on DBus
** Message: va: Stopping PulseAudio
** Message: wlan0: Received scan results

_dhcpcdui.so from 27 May 2016 Raspbian Jessie build running on 27 May 2016 OS_

pi@raspberrypi:~ $ lxpanel -p LXDE-pi
** Message: x-terminal-emulator has very limited support, consider choose another terminal
** Message: Connecting ...
** Message: Status changed to down
** Message: Status changed to opened
** Message: Connected to dhcpcd-6.7.1
** Message: Status changed to connected
** Message: wlan0: Associated with Ramsey-G
** Message: wlan0: Configured 192.168.1.146/24
** Message: wlan0: Received scan results
E: [pulseaudio] main.c: Failed to kill daemon: No such process
** Message: bt: Name org.bluez owned on DBus
** Message: bt: New agent manager found
** Message: bt: No adapter found
** Message: va: Name org.bluez owned on DBus
** Message: va: Stopping PulseAudio
** Message: wlan0: Received scan results

Please let me know if there's anything else I can help with.

Cordially,

Rob

**Comment by ramseyrt** [comment]
Hello Simon,

Regarding the HubPiWi vendor, I contacted him but I haven't heard back.  The Wi-Fi chip on the HubPiWi shows "RealTek rtl8188eus". According to the following link, the Raspbian OS started including the driver for this chip in January 2015:

https://blog.samat.org/2014/12/15/realtek-8188eu-based-wi-fi-adapters-on-the-raspberry-pi/

Kernel support is confirmed in the latest version of Raspbian, released 11 January 2016, based on the output from hwinfo, lsmod, and the boot time log files (messages, syslog, kern.log).

Cordially,

Rob

**Comment by spl237** [comment]
Thanks for the debug output - that all looks pretty much as expected, so I think we may well be looking, as in the previous case I mentioned, at an item of rogue data somewhere in the driver which is confusing the plugin. What I will do is prepare a debug build of the dhcpcdui plugin and send it to you in the next few days; that should hopefully give me enough information to work out where the problem is.

**Comment by ramseyrt** [comment]
Hello Simon,

I performed the procedure to remake the r8188eu driver listed in my previous post.  The newly made driver, based on that post, didn't fix the compatibility issue with the newer dhcpcdui.so.

Cordially,

Rob

**Comment by spl237** [comment]
Hi Rob,

I've built a version of the dhcpcdui.so plugin with a lot of debug in, which should hopefully give me enough information to see what is going wrong. It's at https://www.dropbox.com/s/8a2vhj8dvktmvd0/dhcpcdui.so.zip?dl=0 - please download and unpack it, and install it on the 11 Jan image - it goes in /usr/lib/arm-linux-gnueabihf/lxpanel/plugins, overwriting the one which is already there.

Could you please then repeat "sudo pkill lxpanel" and "lxpanel -p LXDE-pi" from a terminal, and then left-click on the wifi icon on the taskbar - that should produce a full set of debug information in the terminal, which I would then ask you to post here so I can have a look.

For the record, I have tested the new image this morning with a couple of third-party wifi adapters, and they both work correctly, so there is definitely something odd in the Realtek driver. Hopefully the debug output will show me enough to know what it is - we may need to go through the loop a couple of times to narrow it down, so thank you in advance for your patience!

**Comment by ramseyrt** [comment]
Hello Simon,

I've performed the procedure as you requested.  Note that I clicked on the icon a few times and let it run for a little bit.

Please let me know what else I can help with.

Cordially,

Rob

pi@raspberrypi:~ $ lxpanel -p LXDE-pi
** Message: x-terminal-emulator has very limited support, consider choose another terminal
** Message: Connecting ...
** Message: Status changed to down
** Message: Status changed to opened
** Message: Connected to dhcpcd-6.7.1
** Message: Status changed to disconnected
** Message: wlan0: Not associated
** Message: wlan0: WPA status connected
** Message: wlan0: Received scan results
** Message: Null scan - inserting
** Message: Details c0:c1:c0:0a:a9:03 23 2447 Ramsey-G [WPA2-PSK-CCMP][WPS][ESS]
** Message: Interface wlan0 1 8 NOCARRIER 1003 0 1 (null)
E: [pulseaudio] main.c: Failed to kill daemon: No such process
** Message: bt: Name org.bluez owned on DBus
** Message: bt: New agent manager found
** Message: bt: No adapter found
** Message: va: Name org.bluez owned on DBus
** Message: va: Stopping PulseAudio
** Message: Testing for rfkill
** Message: rfkill found
** Message: Can rfkill see hardware?
** Message: Wifi_state = -1 - checking rfkill
** Message: rfkill done
** Message: wifi_enabled -1
** Message: Testing for rfkill
** Message: rfkill found
** Message: Can rfkill see hardware?
** Message: Wifi_state = -1 - checking rfkill
** Message: rfkill done
** Message: wifi_enabled -1
** Message: Testing for rfkill
** Message: rfkill found
** Message: Can rfkill see hardware?
** Message: Wifi_state = -1 - checking rfkill
** Message: rfkill done
** Message: wifi_enabled -1
** Message: wlan0: Received scan results
** Message: Interface matched
** Message: Non-null scan
** Message: wlan0: Received scan results
** Message: Interface matched
** Message: Non-null scan
** Message: wlan0: Received scan results
** Message: Interface matched
** Message: Non-null scan
** Message: Testing for rfkill
** Message: rfkill found
** Message: Can rfkill see hardware?
** Message: Wifi_state = -1 - checking rfkill
** Message: rfkill done
** Message: wifi_enabled -1
** Message: wlan0: Received scan results
** Message: Interface matched
** Message: Non-null scan

**Comment by spl237** [comment]
Hi Rob,

Thanks - that's very helpful, in that I now know where the problem is! It isn't actually the lxpanel plugin itself. 

One of the things we added after the release of Pi 3 was a third-party utility called rfkill, which can be used to turn wireless hardware on and off. This is called from the plugin to determine whether power is enabled to the wireless interfaces - it's used to add the "turn on / turn off wifi" option at the top of the menu (which you currently aren't seeing...)

What is happening is that rfkill is not seeing the wireless hardware on the HubPiWi, and as a result, the plugin (which can see the hardware) is never getting to access it. It looks as if rfkill is not currently compatible with the Realtek hardware on the HubPiWi.

There is a trivial workaround - I designed the plugin so that it would work properly either with or without rfkill. (I wasn't entirely sure why I bothered doing this at the time, but it is about to come in handy for you!) If you uninstall rfkill, I think the plugin will see your hardware and start to work properly.

So take the clean 11 January image - no need for the debug plugin - and from a terminal, execute "sudo apt-get purge rfkill". Reboot, and you should have wifi working in the plugin.

One thing which might be useful is if, before you do that, you run "rfkill list" from a terminal and post the output - it'd be interesting to see if rfkill is detecting anything at all.

It looks as if rfkill is under development - https://wireless.wiki.kernel.org/en/users/documentation/rfkill has some information. It might be worth you posting a message to the linux-wireless mailing list - details at https://wireless.wiki.kernel.org/en/developers/mailinglists - to raise this issue; this is probably the fastest way to get support for the Realtek added to rfkill, as I don't think anyone at Pi has even looked at that particular piece of code.

Try the above - let me know how you get on; I'd hope the workaround of removing rfkill gets you up and running, but please let me know if not.

**Comment by ramseyrt** [comment]
Hello Simon,

When I performed the "rfkill list" nothing was displayed.  After performing
the "apt-get purge rfkill" command, I rebooted.  When the system came up,
everything worked properly.

I file a bug report with the rfkill maintainers and post a link here and on
my HubPiWi trouble-shooting Raspberry Pi form post.

Thanks for all your help,

Rob

**Comment by spl237** [comment]
Hi Rob,

Yes, that fits with what I'd expect to see - rfkill list displaying nothing. Glad the workaround has got you up and running. As this is now known not to be an lxpanel issue, I'll close for now - if you find that you get no joy from the rfkill maintainers, or if they propose a change to the plugin, feel free to reopen.
